export interface Skill {
  name: string;
  icon: string;
}

export type ClipColor = "brand" | "amber" | "violet" | "blue";

/** A single video "clip" on the career timeline. */
export interface TimelineClip {
  /** Track label, e.g. "V3". */
  track: string;
  /** Period chip shown under the track label, e.g. "25 · now". */
  period: string;
  title: string;
  subtitle: string;
  tags: string[];
  color: ClipColor;
  /** Position on the ruler, in the same units as `duration`. */
  start: number;
  /** Length on the ruler. */
  span: number;
}

/** The always-on "audio" track — rendered as a waveform of craft traits. */
export interface AudioClip {
  track: string;
  period: string;
  tags: string[];
  start: number;
  span: number;
}

export interface Timeline {
  /** Total ruler length; clip `start`/`span` are measured against this. */
  duration: number;
  clips: TimelineClip[];
  audio: AudioClip;
}

/** Filter rail for the work galleries — order here is the order shown on
 *  screen. Shared by /work and the "My Work" section on a member page. */
export const WORK_CATEGORIES = [
  "All",
  "Video Editing",
  "Motion Graphics",
  "Photography",
  "Videography",
  "Graphic Designing",
] as const;

export type WorkCategory = (typeof WORK_CATEGORIES)[number];

/** A portfolio piece shown in the "My Work" gallery. */
export interface WorkItem {
  id: string;
  title: string;
  /** 3–5 word line that sits under the title. */
  description: string;
  /** Filter chip this belongs to. */
  category: Exclude<WorkCategory, "All">;
  /** YouTube id — drives both the embed and the poster thumbnail. */
  youtubeId: string;
  /** Domains / services delivered on the project — rendered as pills. */
  tags: string[];
  /** Optional app-logo badge (a path under /public), e.g. a skill icon. */
  tool?: string;
}

export interface TeamMember {
  id: string;
  name: string;
  username: string;
  role: string;
  image: string;
  /** Short line under the name on the detail page. */
  tagline: string;
  bio: string;
  skills: Skill[];
  /** Photos orbiting the portrait on the detail page. Falls back to
   *  DEFAULT_GALLERY — swap in real project stills per person. */
  gallery?: string[];
  /** Career timeline shown on the detail page. When omitted, a role-derived
   *  default is generated by `getTimeline` from the member's own fields. */
  timeline?: Timeline;
  /** Portfolio pieces for the "My Work" gallery. Falls back to DEFAULT_WORK. */
  work?: WorkItem[];
}

/** Placeholder stock photography for the orbiting arc. */
export const DEFAULT_GALLERY: string[] = [
  "/work/1.jpg",
  "/work/2.jpg",
  "/work/3.png",
  "/work/4.png",
  "/work/5.jpg",
  "/work/6.jpg",
  "/work/7.jpg",
  "/work/8.jpg",
  "/work/9.jpg",
  "/work/10.jpg",
  "/work/11.jpg",
  "/work/12.jpg",
  "/work/13.jpg",
];

export const TEAM: TeamMember[] = [
  {
    id: "01",
    name: "Manvaditya Singh",
    username: "manavaditya",
    role: "Motion Designer",
    image: "/team/manavadityasingh.jpeg",
    tagline: "Motion, rhythm and timing",
    bio: "Creating scroll-stopping short-form edits with fast-paced storytelling and seamless transitions.",
    skills: [
      {
        name: "Adobe After Effects",
        icon: "/logos/adobe-after-effects-icon.png",
      },
      {
        name: "Adobe Premiere Pro",
        icon: "/logos/adobe-premiere-pro-icon.png",
      },
    ],
  },
  {
    id: "02",
    name: "Gaurav Agarwal",
    username: "gaurav",
    role: "Lead Photographer",
    image: "/team/gauravagrawal.jpeg",
    tagline: "Light, frame and colour",
    bio: "Using professional editing and color grading software to craft polished, cinematic visuals",
    skills: [
      { name: "DaVinci Resolve", icon: "/logos/DaVinci_Resolve_Studio.png" },
      { name: "Adobe Photoshop", icon: "/logos/adobe-photoshop-icon.png" },
      {
        name: "Adobe Premiere Pro",
        icon: "/logos/adobe-premiere-pro-icon.png",
      },
      {
        name: "Adobe After Effects",
        icon: "/logos/adobe-after-effects-icon.png",
      },
    ],
  },
  {
    id: "03",
    name: "Ritul Tripathi",
    username: "ritul",
    role: "Creative Technologist",
    image: "/team/ritultripathi.jpeg",
    tagline: "Ideas built into pixels",
    bio: "I turn ideas into bold visuals that stand out. From branding and illustrations to animation and graphic design",
    skills: [
      {
        name: "Adobe After Effects",
        icon: "/logos/adobe-after-effects-icon.png",
      },
      { name: "Adobe Illustrator", icon: "/logos/adobe-illustrator-icon.png" },
      { name: "Adobe Photoshop", icon: "/logos/adobe-photoshop-icon.png" },
      { name: "Adobe Lightroom", icon: "/logos/adobe-lightroom-icon.png" },
    ],
  },
  {
    id: "04",
    name: "Arihan Jain",
    username: "arihant",
    role: "Creative Technologist",
    image: "/team/arihanjain.jpg",
    tagline: "Ideas built into pixels",
    bio: "I specialize in flow-style edits, dynamic pacing, and immersive sound design. From viral editing styles to seamless transitions",
    skills: [
      {
        name: "Adobe After Effects",
        icon: "/logos/adobe-after-effects-icon.png",
      },
      {
        name: "Adobe Premiere Pro",
        icon: "/logos/adobe-premiere-pro-icon.png",
      },
    ],
  },
  {
    id: "05",
    name: "Herain Deegwal",
    username: "herain",
    role: "Creative Technologist",
    image: "/team/Herain.jpg",
    tagline: "Ideas built into pixels",
    bio: "Always chasing the perfect frame. From photography and cinematography to camera handling, I create clean, cinematic visuals with purpose where every frame tells a story.",
    skills: [
      { name: "Adobe Illustrator", icon: "/logos/adobe-illustrator-icon.png" },
      { name: "Adobe Photoshop", icon: "/logos/adobe-photoshop-icon.png" },
    ],
  },
  {
    id: "06",
    name: "Bharat Kumar",
    username: "bharat",
    role: "Photography/Cinematography",
    image: "/team/bharat.JPG",
    tagline: "Ideas built into pixels",
    bio: "A photographer and videographer capturing fresh, authentic moments with a cinematic touch. From quirky visuals to modern vlogs, I bring creativity and energy to every frame.",
    skills: [
      { name: "Adobe Photoshop", icon: "/logos/adobe-photoshop-icon.png" },
      { name: "Adobe Illustrator", icon: "/logos/adobe-illustrator-icon.png" },
      {
        name: "Adobe Premiere Pro",
        icon: "/logos/adobe-premiere-pro-icon.png",
      },
    ],
  },
  {
    id: "07",
    name: "Kunal Tak",
    username: "kunal",
    role: "Video Editor/ Motion Designer",
    image: "/team/kunal.jpg",
    tagline: "Ideas built into pixels",
    bio: "Turning ideas into motion with sleek animations and dynamic video edits that are clean, engaging, and built to stand out",
    skills: [
      { name: "Adobe Illustrator", icon: "/logos/adobe-illustrator-icon.png" },
      { name: "Adobe Photoshop", icon: "/logos/adobe-photoshop-icon.png" },
      { name: "Blender", icon: "/logos/blender.png" },
    ],
  },
];

export function getMemberByUsername(username: string) {
  return TEAM.find((member) => member.username === username);
}

const STOP_WORDS = new Set([
  "into",
  "with",
  "and",
  "the",
  "of",
  "for",
  "a",
  "an",
  "to",
  "on",
  "in",
]);

function titleCase(word: string) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

/** Turn a tagline into a few "craft" words for the audio waveform track.
 *  "Motion, rhythm and timing" -> ["Motion", "Rhythm", "Timing"]. */
function craftWords(tagline: string): string[] {
  let parts = tagline
    .split(/,|\band\b/i)
    .map((part) => part.trim())
    .filter(Boolean);

  if (parts.length < 2) {
    parts = tagline
      .split(/\s+/)
      .filter((word) => word.length > 2 && !STOP_WORDS.has(word.toLowerCase()));
  }

  return parts.slice(0, 3).map(titleCase);
}

/** Short, tool-name tags: "Adobe After Effects" -> "After Effects". */
function skillTags(member: TeamMember): string[] {
  return member.skills.map((skill) => skill.name.replace(/^Adobe\s+/, ""));
}

/** The member's own timeline, or an honest default assembled from their role,
 *  skills and tagline — no fabricated employers or dates. */
export function getTimeline(member: TeamMember): Timeline {
  if (member.timeline) return member.timeline;

  const tools = skillTags(member);

  return {
    duration: 24,
    clips: [
      {
        track: "V3",
        period: "Now",
        title: "Blitz Pixel Media",
        subtitle: `${member.role} · Present`,
        tags: [...tools.slice(0, 2), "Bangalore"],
        color: "brand",
        start: 0,
        span: 22,
      },
      {
        track: "V2",
        period: "Craft",
        title: "Studio & Client Work",
        subtitle: "Sharpening the reel",
        tags: tools.slice(0, 3),
        color: "amber",
        start: 0,
        span: 18,
      },
      {
        track: "V1",
        period: "Roots",
        title: "Learning the Craft",
        subtitle: "Where it started",
        tags: ["Curiosity", "Practice"],
        color: "violet",
        start: 0,
        span: 11,
      },
    ],
    audio: {
      track: "A1",
      period: "Always",
      tags: craftWords(member.tagline),
      // Runs the full length of the sequence (00:00 → duration).
      start: 0,
      span: 24,
    },
  };
}

/** Placeholder portfolio — swap `member.work` in with real project videos.
 *  Uses open-content YouTube ids so the embeds and posters resolve. */
export const DEFAULT_WORK: WorkItem[] = [
  {
    id: "w1",
    title: "Acne Scars",
    description: "Skincare reel cut for retention and clean pacing.",
    category: "Video Editing",
    youtubeId: "aqz-KE-bpKQ",
    tags: ["Med Spa", "Social Media"],
    tool: "/logos/adobe-premiere-pro-icon.png",
  },
  {
    id: "w2",
    title: "Take It At Night",
    description: "Night-routine promo built around a single hook.",
    category: "Video Editing",
    youtubeId: "eRsGyueVLvQ",
    tags: ["Promo", "Colour Grade"],
    tool: "/logos/adobe-premiere-pro-icon.png",
  },
  {
    id: "w3",
    title: "Jaw Dropper",
    description: "Kinetic brand ad driven by bold type.",
    category: "Motion Graphics",
    youtubeId: "R6MlUcmOul8",
    tags: ["Advertisement", "Animation"],
    tool: "/logos/adobe-after-effects-icon.png",
  },
  {
    id: "w4",
    title: "Kinetic Type",
    description: "Typography animation with layered sound design.",
    category: "Motion Graphics",
    youtubeId: "TLkA0RELQ1g",
    tags: ["Titles", "Sound Design"],
    tool: "/logos/adobe-after-effects-icon.png",
  },
  {
    id: "w5",
    title: "Studio Sessions",
    description: "Multi-cam podcast set, shot and lit in-house.",
    category: "Videography",
    youtubeId: "LXb3EKWsInQ",
    tags: ["Podcast", "Multi-Cam"],
    tool: "/logos/DaVinci_Resolve_Studio.png",
  },
  {
    id: "w6",
    title: "Launch Day",
    description: "Product launch film shot across one day.",
    category: "Videography",
    youtubeId: "ScMzIvxBSi4",
    tags: ["Brand Film", "Direction"],
    tool: "/logos/DaVinci_Resolve_Studio.png",
  },
  {
    id: "w7",
    title: "Lookbook 01",
    description: "Studio product stills retouched for campaign use.",
    category: "Photography",
    youtubeId: "eRsGyueVLvQ",
    tags: ["Product", "Retouching"],
    tool: "/logos/adobe-lightroom-icon.png",
  },
  {
    id: "w8",
    title: "Portrait Series",
    description: "Founder portraits shot for a rebrand rollout.",
    category: "Photography",
    youtubeId: "LXb3EKWsInQ",
    tags: ["Editorial", "Colour Grade"],
    tool: "/logos/adobe-photoshop-icon.png",
  },
  {
    id: "w9",
    title: "AXN",
    description: "Minimal streetwear identity with bold attitude.",
    category: "Graphic Designing",
    youtubeId: "R6MlUcmOul8",
    tags: ["Branding", "Social Media"],
    tool: "/logos/adobe-illustrator-icon.png",
  },
  {
    id: "w10",
    title: "Rivermark",
    description: "Street campaign system built to grab attention.",
    category: "Graphic Designing",
    youtubeId: "TLkA0RELQ1g",
    tags: ["Campaign", "Print"],
    tool: "/logos/adobe-photoshop-icon.png",
  },
];

/** The member's own portfolio, or the shared placeholder set. */
export function getWork(member: TeamMember): WorkItem[] {
  return member.work?.length ? member.work : DEFAULT_WORK;
}
