export interface Skill {
  name: string;
  icon: string;
}

export type ClipColor = 'brand' | 'amber' | 'violet' | 'blue';

/** A single video "clip" on the career timeline. */
export interface TimelineClip {
  /** Track label, e.g. "V3". */
  track: string;
  /** Period chip shown under the track label, e.g. "25 · now". */
  period: string;
  title: string;
  subtitle: string;
  tags: string[];
  color: ClipColor;
  /** Position on the ruler, in the same units as `duration`. */
  start: number;
  /** Length on the ruler. */
  span: number;
}

/** The always-on "audio" track — rendered as a waveform of craft traits. */
export interface AudioClip {
  track: string;
  period: string;
  tags: string[];
  start: number;
  span: number;
}

export interface Timeline {
  /** Total ruler length; clip `start`/`span` are measured against this. */
  duration: number;
  clips: TimelineClip[];
  audio: AudioClip;
}

/** A portfolio piece shown in the "My Work" gallery. */
export interface WorkItem {
  id: string;
  title: string;
  /** Filter chip this belongs to, e.g. "Med Spa", "Advertisement". */
  category: string;
  /** YouTube id — drives both the embed and the poster thumbnail. */
  youtubeId: string;
  /** Optional app-logo badge (a path under /public), e.g. a skill icon. */
  tool?: string;
}

export interface TeamMember {
  id: string;
  name: string;
  username: string;
  role: string;
  image: string;
  /** Short line under the name on the detail page. */
  tagline: string;
  skills: Skill[];
  /** Photos orbiting the portrait on the detail page. Falls back to
   *  DEFAULT_GALLERY — swap in real project stills per person. */
  gallery?: string[];
  /** Career timeline shown on the detail page. When omitted, a role-derived
   *  default is generated by `getTimeline` from the member's own fields. */
  timeline?: Timeline;
  /** Portfolio pieces for the "My Work" gallery. Falls back to DEFAULT_WORK. */
  work?: WorkItem[];
}

/** Placeholder stock photography for the orbiting arc. */
export const DEFAULT_GALLERY: string[] = [
  'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05',
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e',
  'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
  'https://images.unsplash.com/photo-1502082553048-f009c37129b9',
  'https://images.unsplash.com/photo-1494548162494-384bba4ab999',
  'https://images.unsplash.com/photo-1483347756197-71ef80e95f73',
  'https://images.unsplash.com/photo-1518709268805-4e9042af9f23',
  'https://images.unsplash.com/photo-1487958449943-2429e8be8625',
  'https://images.unsplash.com/photo-1439066615861-d1af74d74000',
  'https://images.unsplash.com/photo-1510784722466-f2aa9c52fff6',
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
  'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d',
  'https://images.unsplash.com/photo-1444927714506-8492d94b4e3d',
];

export const TEAM: TeamMember[] = [
  {
    id: '01',
    name: 'Manvaditya Singh',
    username: 'manavaditya',
    role: 'Motion Designer',
    image: '/team/manavadityasingh.jpeg',
    tagline: 'Motion, rhythm and timing',
    skills: [
      { name: 'Adobe After Effects', icon: '/logos/adobe-after-effects-icon.png' },
      { name: 'Adobe Premiere Pro', icon: '/logos/adobe-premiere-pro-icon.png' },
    ],
  },
  {
    id: '02',
    name: 'Gaurav Agarwal',
    username: 'gaurav',
    role: 'Lead Photographer',
    image: '/team/gauravagrawal.jpeg',
    tagline: 'Light, frame and colour',
    skills: [
      { name: 'DaVinci Resolve', icon: '/logos/DaVinci_Resolve_Studio.png' },
      { name: 'Adobe Photoshop', icon: '/logos/adobe-photoshop-icon.png' },
      { name: 'Adobe Premiere Pro', icon: '/logos/adobe-premiere-pro-icon.png' },
      { name: 'Adobe After Effects', icon: '/logos/adobe-after-effects-icon.png' },
    ],
  },
  {
    id: '03',
    name: 'Ritul Tripathi',
    username: 'ritul',
    role: 'Creative Technologist',
    image: '/team/ritultripathi.jpeg',
    tagline: 'Ideas built into pixels',
    skills: [
      { name: 'Adobe After Effects', icon: '/logos/adobe-after-effects-icon.png' },
      { name: 'Adobe Illustrator', icon: '/logos/adobe-illustrator-icon.png' },
      { name: 'Adobe Photoshop', icon: '/logos/adobe-photoshop-icon.png' },
      { name: 'Adobe Lightroom', icon: '/logos/adobe-lightroom-icon.png' },
    ],
  },
  {
    id: '04',
    name: 'Arihan Jain',
    username: 'arihant',
    role: 'Creative Technologist',
    image: '/team/arihantjain.jpg',
    tagline: 'Ideas built into pixels',
    skills: [
      { name: 'Adobe After Effects', icon: '/logos/adobe-after-effects-icon.png' },
      { name: 'Adobe Premiere Pro', icon: '/logos/adobe-premiere-pro-icon.png' },
    ],
  },
  {
    id: '05',
    name: 'Herain Deegwal',
    username: 'herain',
    role: 'Creative Technologist',
    image: '/team/Herain.jpg',
    tagline: 'Ideas built into pixels',
    skills: [
      { name: 'Adobe Illustrator', icon: '/logos/adobe-illustrator-icon.png' },
      { name: 'Adobe Photoshop', icon: '/logos/adobe-photoshop-icon.png' },
    ],
  },
];

export function getMemberByUsername(username: string) {
  return TEAM.find((member) => member.username === username);
}

const STOP_WORDS = new Set([
  'into', 'with', 'and', 'the', 'of', 'for', 'a', 'an', 'to', 'on', 'in',
]);

function titleCase(word: string) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

/** Turn a tagline into a few "craft" words for the audio waveform track.
 *  "Motion, rhythm and timing" -> ["Motion", "Rhythm", "Timing"]. */
function craftWords(tagline: string): string[] {
  let parts = tagline
    .split(/,|\band\b/i)
    .map((part) => part.trim())
    .filter(Boolean);

  if (parts.length < 2) {
    parts = tagline
      .split(/\s+/)
      .filter((word) => word.length > 2 && !STOP_WORDS.has(word.toLowerCase()));
  }

  return parts.slice(0, 3).map(titleCase);
}

/** Short, tool-name tags: "Adobe After Effects" -> "After Effects". */
function skillTags(member: TeamMember): string[] {
  return member.skills.map((skill) => skill.name.replace(/^Adobe\s+/, ''));
}

/** The member's own timeline, or an honest default assembled from their role,
 *  skills and tagline — no fabricated employers or dates. */
export function getTimeline(member: TeamMember): Timeline {
  if (member.timeline) return member.timeline;

  const tools = skillTags(member);

  return {
    duration: 24,
    clips: [
      {
        track: 'V3',
        period: 'Now',
        title: 'Blitz Pixel Media',
        subtitle: `${member.role} · Present`,
        tags: [...tools.slice(0, 2), 'Bangalore'],
        color: 'brand',
        start: 2,
        span: 20,
      },
      {
        track: 'V2',
        period: 'Craft',
        title: 'Studio & Client Work',
        subtitle: 'Sharpening the reel',
        tags: tools.slice(0, 3),
        color: 'amber',
        start: 2,
        span: 16,
      },
      {
        track: 'V1',
        period: 'Roots',
        title: 'Learning the Craft',
        subtitle: 'Where it started',
        tags: ['Curiosity', 'Practice'],
        color: 'violet',
        start: 2,
        span: 9,
      },
    ],
    audio: {
      track: 'A1',
      period: 'Always',
      tags: craftWords(member.tagline),
      start: 2,
      span: 20,
    },
  };
}

/** Placeholder portfolio — swap `member.work` in with real project videos.
 *  Uses open-content YouTube ids so the embeds and posters resolve. */
export const DEFAULT_WORK: WorkItem[] = [
  {
    id: 'w1',
    title: 'Acne Scars — Skincare Reel',
    category: 'Med Spa',
    youtubeId: 'aqz-KE-bpKQ',
    // tool: '/logos/adobe-photoshop-icon.png',
  },
  {
    id: 'w2',
    title: 'Take It At Night — Promo',
    category: 'Med Spa',
    youtubeId: 'eRsGyueVLvQ',
    // tool: '/logos/adobe-after-effects-icon.png',
  },
  {
    id: 'w3',
    title: 'Jaw Dropper — Brand Ad',
    category: 'Advertisement',
    youtubeId: 'R6MlUcmOul8',
    // tool: '/logos/adobe-premiere-pro-icon.png',
  },
  {
    id: 'w4',
    title: 'Studio Sessions — Podcast Cut',
    category: 'Podcast',
    youtubeId: 'LXb3EKWsInQ',
  },
  {
    id: 'w5',
    title: 'Kinetic Type — Animation',
    category: 'Animation',
    youtubeId: 'TLkA0RELQ1g',
    // tool: '/logos/adobe-after-effects-icon.png',
  },
  {
    id: 'w6',
    title: 'Launch Day — Social Reel',
    category: 'Social Media',
    youtubeId: 'ScMzIvxBSi4',
  },
];

/** The member's own portfolio, or the shared placeholder set. */
export function getWork(member: TeamMember): WorkItem[] {
  return member.work?.length ? member.work : DEFAULT_WORK;
}
